openapi: 3.1.0
info:
  title: FastAPI service for ML-project
  version: 0.0.1
  description: |
    Mental health diagnosing service. /p
    Authors:
    - Aleksandr Algazinov @krasnorechivyy
    - Bogdan Gabovskiy @Gdsgft
    - Alexey Ryzhov @Aleksey_1337228
    - Kozhevnikov Ilya @borbarsik
servers:
  - url: https://localhost:8080

tags:
  - name: History
    description: Operations with history of requests
  - name: Predict
    description: Diagnosis predictions

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      required: [ id, login ]
      properties:
        id: { type: string, format: uuid }
        login: { type: string }
        name: { type: string, nullable: true }

    PromptCreateRequest:
      type: object
      required: [ message ]
      properties:
        message: { type: string, minLength: 200, maxLength: 1000 }

    Diagnosis:
      type: object
      required: [ label, riskLevel ]
      properties:
        label: { type: string }
        confidence: { type: number, format: float, minimum: 0, maximum: 1 }
        riskLevel: { type: string, enum: [ LOW, MEDIUM, HIGH ] }
        recommendations: { type: string, nullable: true }

    PromptDiagnosisResponse:
      type: object
      required: [ id, diagnosis ]
      properties:
        id: { type: string, format: uuid }
        diagnosis: { $ref: "#/components/schemas/Diagnosis" }

    PromptRecord:
      type: object
      required: [ id, createdAt, promptId, status ]
      properties:
        id: { type: string, format: uuid }
        promptId: { type: string, format: uuid }
        message: { type: string }
        createdAt: { type: string, format: date-time }
        diagnosis: { $ref: "#/components/schemas/Diagnosis", nullable: true }
        status: { type: string, enum: [ PENDING, SUCCESS, FAILED ] }

    PromptHistoryResponse:
      type: object
      required: [ items ]
      properties:
        items:
          type: array
          items: { $ref: "#/components/schemas/PromptRecord" }
        nextCursor:
          type: string
          nullable: true

    StatsResponse:
      type: object
      required: [ latencyMs, input, window, count ]
      properties:
        latencyMs:
          type: object
          required: [ mean, p50, p95, p99 ]
          properties:
            mean: { type: number, format: float }
            p50: { type: number, format: float }
            p95: { type: number, format: float }
            p99: { type: number, format: float }
        input:
          type: object
          required: [ avgLength, avgTokens, p95Tokens ]
          properties:
            avgLength: { type: number, format: float }
            avgTokens: { type: number, format: float }
            p95Tokens: { type: number, format: float }
        window:
          type: object
          required: [ from, to ]
          properties:
            from: { type: string, format: date-time }
            to: { type: string, format: date-time }
        count: { type: integer, minimum: 0 }

    ProblemDetails:
      type: object
      required: [ type, title, status ]
      properties:
        type: { type: string, format: uri }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
        instance: { type: string, format: uri }


security:
  - bearerAuth: [ ]

paths: #TODO
